### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dsielert** [webhippie/redirects#53]
No documentation? URL to github.io is dead

**Comment by tboerger** [comment]
This project will anyway receive some updates soon, than I will also add some simple documentation.

If I don't forget it I will post an example config tomorrow :)

**Comment by dsielert** [comment]
Awesome! Yeah that'd be great.. I think this project would be of help for something I'm working on.. Appreciate your work !

**Comment by dsielert** [comment]
I toyed around with this and figured a bunch out , but maybe I'm mistaken does this support full hostname redirects?

**Comment by tboerger** [comment]
Finally there is a 1.0.0 release and some basic documentation.
